version: "3.9"
services:
  redis:
    image: redis:7-alpine
    container_name: lms-redis
    ports: ["6379:6379"]
    command: ["redis-server", "--append-only", "yes"]
    volumes:
      - redisdata:/data
  flower:
    image: mher/flower:latest
    container_name: lms-flower
    environment:
      - FLOWER_PORT=5555
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    ports: ["5555:5555"]
    depends_on: [redis]
volumes:
  redisdata: